Update GIT

diff --git a/GIT b/GIT
--- a/GIT
+++ b/GIT
@@ -8,8 +8,15 @@ ls -ltr
 git branch --list
 git add newfolder
 git status
-git commit -m "Added new"
-git branch --list
-git status
+set +e #Grep succeeds with nonzero exit codes to show results.
+git status | grep modified
+if [ $? -eq 0 ]
+then
+set -e
+git commit -am "Added new"
 #git push -u origin/develop
 git push git@git.domain.com:projectname/jobname.git HEAD:develop -f # timeout=10
+else
+set -e
+echo "No changes to configuration since last run."
+fi
